services:
  mysql:
    image: mysql:8.0
    container_name: airflow_databases
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pramuka123@
      MYSQL_DATABASE: django-app-airflow_database
    ports:
      - "3012:3012"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:latest
    container_name: airflow_init
    depends_on:
      mysql:
        condition: service_healthy
      
    environment:
      AIRFLOW_CORE_EXECUTOR: SequentialExecutor
      AIRFLOW_DATABASE_SQL_ALCHEMY_CONN: "mysql+pymysql://root:Pramuka2345%40@mysql:3306/django-app-database"
      AIRFLOW_CORE_LOAD_EXAMPLES: "False"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    entrypoint: ["/bin/bash", "-c", "airflow db init"]
    restart: "no"

  airflow-webserver:
    image: apache/airflow:latest
    container_name: airflow-webserver
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW_CORE_EXECUTOR: SequentialExecutor
      AIRFLOW_DATABASE_SQL_ALCHEMY_CONN: "mysql+pymysql://root:Pramuka123%40@mysql:3306/django-app-database"
      AIRFLOW_WEBSERVER_SECRET_KEY: ngabngab
      AIRFLOW_CORE_LOAD_EXAMPLES: "False"
    ports:
      - "3425:3425"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: ["webserver"]

  airflow-scheduler:
    image: apache/airflow:latest
    container_name: airflow-scheduler
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW_CORE_EXECUTOR: SequentialExecutor
      AIRFLOW_DATABASE_SQL_ALCHEMY_CONN: "mysql+pymysql://root:Pramuka123%40@mysql:3306/django-app-database"
      AIRFLOW_CORE_LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: ["scheduler"]
volumes:
  mysql_data:
